### ISSUE TITLE
Kibana 7.x compatibility issue

### ISSUE THREAD

**Issue by yesnid** [walterra/kibana-milestones-vis#7]
Hello,

I am trying to use your visualization in my Kibana but the ony aggregation it allows me is

> Dummy Metric Aggregation

of type count, and when i try to use it doesn't seem to render anything what suggestions do you have?

**Comment by walterra** [comment]
So far there've been only releases for `7.0.0` alpha versions. Today I released updated versions for the most recent Elastic Stack releases: https://github.com/walterra/kibana-milestones-vis/releases

Please make sure you run the exact same version of the plugin on the version of Kibana you're using. Let me know if it works for you! Would also love to learn about your use case, if you're willing to share, let's catch up on via twitter.com/walterra

**Comment by yesnid** [comment]
OKay I uninstalled my hacked version, and then installed your released version but I still get nothing rendered when I try to use your plugin as a visualization, and it still has "Dummy Aggregation" with only count allowed as an aggregation, any ideas?

**Comment by walterra** [comment]
Please let me know the exact version you downloaded and I'll try to reproduce, thanks!

**Comment by yesnid** [comment]
I am working with this release: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.1.0, and the corresponding releases of kibana, and elastic. After a reboot of the server I get a visualization, but... It still only offers "Dummy Aggregation" with only count allowed as an aggregation, any ideas?

**Comment by peteharverson** [comment]
@yesnid thanks for the extra info. Just to update you, the maintainer of this plugin @walterra is currently off on holiday, but will take a look when he returns.

**Comment by walterra** [comment]
Hey @yesnid,

By default the plugin only adds the `Dummy Metric Aggregation` to the `Metrics` Section. I haven't found a way for the plugin to work around that, the data created in the `Metrics` section is not really necessary for the visualization itself, but Kibana kind of requires that. So it should just be there and there's no need to change it.

You should see additional options in the `Buckets` section below though:

![image](https://user-images.githubusercontent.com/230104/59783072-981da800-92bf-11e9-9f41-66134f2db768.png)

For `X-Axis` you should pick a date field and do a `date_histogram` like this for example:

![image](https://user-images.githubusercontent.com/230104/59783296-2134df00-92c0-11e9-8d03-605cb2415190.png)

For `Milestones Labels` you should do a `terms` agg on the field you want to use as a label, for example:

![image](https://user-images.githubusercontent.com/230104/59783393-59d4b880-92c0-11e9-966a-592758405323.png)

Let me know if you can see those options in the interface and if this works for you.

**Comment by walterra** [comment]
I'm closing this since I haven't heard from you in a while. Feel free to reopen if the suggestions above don't work for you.
